### ISSUE TITLE
Use crypto/rand instead of math/rand

### ISSUE THREAD

**Issue by elithrar** [dinever/golf#20]
[`randomBytes`](https://github.com/dinever/golf/blob/7a06be0db26a0fb2694cec1bf381ba75f254df87/xsrf.go#L11) in xsrf.go uses `math.rand` to generate CSRF tokens. This is unsafe/insecure, and because it is seeded with `time.UnixNano`, generates predictable results that would allow an attacker to bypass CSRF protection.

[`sessionID`](https://github.com/dinever/golf/blob/7a06be0db26a0fb2694cec1bf381ba75f254df87/session.go#L38) in session.go correctly uses `crypto/rand` to generate a session ID. You should split this code out and re-use it for both session ID generation _and_ CSRF token generation.

(You're also welcome to import or repurpose https://github.com/gorilla/csrf for this as well, which has some additional mitigations against CSRF bypass)

**Comment by elithrar** [comment]
(I'll also gladly provide a PR to address this, but wanted to get buy in/explain it first!)

**Comment by dinever** [comment]
@elithrar Thanks for pointing this out. Please feel free to open a PR.

https://github.com/gorilla/csrf looks really nice. I would prefer to repurpose it and put a credit in the `README`. Thanks again!

**Comment by elithrar** [comment]
OK, great. To clarify, I plan on:

* Making sure `crypto/rand` is the only way tokens are generated throughout the framework (first and foremost)
* Import gorilla/csrf for generating CSRF tokens (second)

I'd strongly recommend that you import gorilla/csrf—which has a strict API stability guarantee, but would also be vendored by downstream users—rather than copying the code into your library so that any security patches or feature additions are kept in-sync. Ultimately that's up to you though.
