### ISSUE TITLE
Update tag version

### ISSUE THREAD

**Issue by dogrocker** [dinever/golf#25]
Hello I'm use `gopkg` to download the dependency by using `go get gopkg.in/dinever/golf.v0`.

It download the v0.2 not a master branch. and it not provide some function in docs. Like `Context.SetHeder(), Contextext.sendStatus(), app.Use()`, that master branch have.

Thank you.

**Comment by dinever** [comment]
Thanks for the feedback @dogrocker, I've updated the repo with a new tag.
