### ISSUE TITLE
Why default redirect is use 301?

### ISSUE THREAD

**Issue by dogrocker** [dinever/golf#26]
Hello, I have question about Redirect function. Why Golf use 301 not 302 by default. Because I think redirect with 302 use more than 301. So Is default value should be 302?.

And another problem with 301 is browser will cache the redirection even if you disabled the redirection from the server level.
ref: http://stackoverflow.com/questions/1393280/http-redirect-301-permanent-vs-302-temporary

Thanks for created Golf, I just question and suggestion. Sorry for my bad english.

**Comment by dinever** [comment]
Nice catch! @dogrocker

This has been fixed in #27 

I'm sorry for this late response since I didn't get much time on open-source projects in the last several months.
